name: NetBSD

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: macos-12
    
    strategy:
      fail-fast: false
      matrix:
        version: [9]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: vagrant-generic-netbsd-${{ matrix.version }}
          restore-keys: |
            vagrant-generic-netbsd-${{ matrix.version }}

      - uses: leleliu008/github-actions-vagrant@v1
        with:
          mem: 2048
          box: generic/netbsd${{ matrix.version }}
          run: |
            run sudo pkgin -y install cmake ninja-build pkg-config clang curl libarchive libyaml

            run cmake -S . -B   build.d -G Ninja -DCMAKE_INSTALL_PREFIX=./output -DCMAKE_VERBOSE_MAKEFILE=ON
            run cmake --build   build.d
            run cmake --install build.d


            export LD_LIBRARY_PATH=/usr/pkg/lib

            run sudo rm -rf /usr/pkg/etc/openssl
            run sudo pkgin -y install mozilla-rootcerts
            run sudo mozilla-rootcerts install

            if [ ${{matrix.version}} -eq 8 ] ; then
                export SSL_CERT_FILE=/usr/pkg/etc/openssl/certs/ca-certificates.crt
            else
                export SSL_CERT_FILE=/etc/openssl/certs/ca-certificates.crt
            fi


            run ./output/bin/python3-setup

            run ./output/bin/python3-setup --help
            run ./output/bin/python3-setup -h

            run ./output/bin/python3-setup --version
            run ./output/bin/python3-setup -V

            run ./output/bin/python3-setup sysinfo

            run ./output/bin/python3-setup env

            run ./output/bin/python3-setup show-default-config


            run ./output/bin/python3-setup setup -v

            export PATH="$HOME/.python3-setup/python3/bin:$PATH"
            run pip3 install meson


           #run ./output/bin/python3-setup upgrade-self
