name: publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:

  check:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - id:  check-if-has-new-commit
        run: |
          cat > QUERY <<EOF
          {
            repository(owner: "leleliu008", name: "python3-setup") {
                latestRelease {
                  name
                }
            }
          }
          EOF

          LATEST_RELEASE_GIT_SHA="$(gh api graphql -f "query=$(cat QUERY)" --jq .data.repository.latestRelease.name | cut -d+ -f2)"

          printf 'LATEST_RELEASE_GIT_SHA=%s\n' "$LATEST_RELEASE_GIT_SHA"

          CURRENT_SOURCE_GIT_SHA=${{ github.sha }}

          printf 'CURRENT_SOURCE_GIT_SHA=%s\n' "$CURRENT_SOURCE_GIT_SHA"


          if [ "$LATEST_RELEASE_GIT_SHA" = "$CURRENT_SOURCE_GIT_SHA" ] ; then
              printf 'HAS_NEW_COMMIT=no\n'        >> "$GITHUB_OUTPUT"
          else
              printf 'HAS_NEW_COMMIT=yes\n'       >> "$GITHUB_OUTPUT"
          fi

          printf 'GIT_SHA=%s\n' "$CURRENT_SOURCE_GIT_SHA" >> "$GITHUB_OUTPUT"

    outputs:
      if-has-new-commit: ${{ steps.check-if-has-new-commit.outputs.HAS_NEW_COMMIT }}
      git-sha:           ${{ steps.check-if-has-new-commit.outputs.GIT_SHA }}


  netbsd-amd64:
    needs: check
    if: needs.check.outputs.if-has-new-commit == 'yes'

    runs-on: macos-12

    steps:
      - uses: leleliu008/github-actions-vagrant@main
        with:
          mem: 2048
          box: generic/netbsd9
          run: |
            export HOME=/home/vagrant

            run sudo sed -i 's/#ETCCERTSDIR=/ETCCERTSDIR=/' /usr/pkg/etc/ca-certificates-dir.conf
            run sudo update-ca-certificates

            unset ETCCERTSDIR

            ETCCERTSDIR=$(sed -n '/^ETCCERTSDIR=/p' /usr/pkg/etc/ca-certificates-dir.conf | sed 's|ETCCERTSDIR=\(.*\)|\1|')

            if [ -n "$ETCCERTSDIR" ] ; then
                export SSL_CERT_FILE="$ETCCERTSDIR/ca-certificates.crt"
            fi

            run curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
            run chmod a+x ppkg
            run ./ppkg setup --use-system-package-manager
            run ./ppkg update

            gsed -i "/git-url/a git-sha: ${{ needs.check.outputs.git-sha }}" ~/.ppkg/repos.d/offical-core/formula/python3-setup.yml

            run ./ppkg install python3-setup --link-type=static-only --install-lib=static
            run ./ppkg pack    python3-setup

      - run: scp -i $VAGRANT_CWD/.vagrant/machines/default/virtualbox/private_key -o StrictHostKeyChecking=no -r -P 2222 vagrant@127.0.0.1:/home/vagrant/.ppkg/packed/python3-setup-*-netbsd-amd64.tar.xz .

      - uses: actions/upload-artifact@v3
        with:
          name: python3-setup---netbsd-amd64-tar-xz
          path: python3-setup-*-netbsd-amd64.tar.xz

  openbsd-amd64:
    needs: [check, netbsd-amd64]
    if: needs.check.outputs.if-has-new-commit == 'yes'

    runs-on: macos-12

    steps:
      - run: brew install openssh

      - uses: leleliu008/github-actions-vagrant@main
        with:
          mem: 2048
          box: generic/openbsd7
          run: |
            run sudo pkg_add curl

            export HOME=/home/vagrant
            export LD_LIBRARY_PATH=/usr/local/lib

            run sudo ln -sf /usr/local/bin/pkgconf /usr/bin/pkg-config

            run curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
            run chmod a+x ppkg
            run ./ppkg setup --use-system-package-manager
            run ./ppkg update

            gsed -i "/git-url/a git-sha: ${{ needs.check.outputs.git-sha }}" ~/.ppkg/repos.d/offical-core/formula/python3-setup.yml

            run ./ppkg install python3-setup --link-type=static-only --install-lib=static
            run ./ppkg pack    python3-setup

      - run: scp -i $VAGRANT_CWD/.vagrant/machines/default/virtualbox/private_key -o StrictHostKeyChecking=no -r -P 2222 vagrant@127.0.0.1:/home/vagrant/.ppkg/packed/python3-setup-*-openbsd-amd64.tar.xz .

      - uses: actions/upload-artifact@v3
        with:
          name: python3-setup---openbsd-amd64-tar-xz
          path: python3-setup-*-openbsd-amd64.tar.xz

  freebsd-amd64:
    needs: [check, openbsd-amd64]
    if: needs.check.outputs.if-has-new-commit == 'yes'

    runs-on: macos-12

    steps:
      - uses: leleliu008/github-actions-vagrant@main
        with:
          mem: 2048
          box: generic/freebsd13
          run: |
            export HOME=/home/vagrant

            run pkg install -y curl libnghttp2

            run curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
            run chmod a+x ppkg
            run ./ppkg setup --use-system-package-manager
            run ./ppkg update

            gsed -i "/git-url/a git-sha: ${{ needs.check.outputs.git-sha }}" ~/.ppkg/repos.d/offical-core/formula/python3-setup.yml

            run ./ppkg install python3-setup --link-type=static-only --install-lib=static
            run ./ppkg pack    python3-setup

      - run: scp -i $VAGRANT_CWD/.vagrant/machines/default/virtualbox/private_key -o StrictHostKeyChecking=no -r -P 2222 vagrant@127.0.0.1:/home/vagrant/.ppkg/packed/python3-setup-*-freebsd-amd64.tar.xz .

      - uses: actions/upload-artifact@v3
        with:
          name: python3-setup---freebsd-amd64-tar-xz
          path: python3-setup-*-freebsd-amd64.tar.xz

  macos:
    needs: [check, freebsd-amd64]
    if: needs.check.outputs.if-has-new-commit == 'yes'

    runs-on: macos-12

    strategy:
      fail-fast: false
      matrix:
        target-version: ['11.0', '12.0', '13.0']
        target-arch: [x86_64, arm64]

    steps:
      - run: brew uninstall go@1.17
      - run: brew update
      - run: brew install --overwrite python@3.10 python@3.11

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/xcpkg/master/xcpkg
      - run: chmod a+x xcpkg
      - run: ./xcpkg setup --use-brew
      - run: ./xcpkg update

      - run: |
          gsed -i "/git-url/a git-sha: ${{ needs.check.outputs.git-sha }}" ~/.xcpkg/repos.d/offical-core/formula/python3-setup.yml

      - run: ./xcpkg install MacOSX/${{ matrix.target-version }}/${{ matrix.target-arch }}/python3-setup --link-type=static-prefered --install-lib=static
      - run: ./xcpkg pack    MacOSX/${{ matrix.target-version }}/${{ matrix.target-arch }}/python3-setup -o .

      - uses: actions/upload-artifact@v3
        with:
          name: python3-setup---macos${{ matrix.target-version }}-${{ matrix.target-arch }}-tar-xz
          path: python3-setup-*-macos*.tar.xz


  linux-aarch64:
    needs: [check, macos]
    if: needs.check.outputs.if-has-new-commit == 'yes'

    runs-on: ubuntu-latest

    steps:
      - run: |
          cat > run.sh <<EOF
          set -e

          COLOR_GREEN='\033[0;32m'        # Green
          COLOR_PURPLE='\033[0;35m'       # Purple
          COLOR_OFF='\033[0m'             # Reset

          echo() {
              printf '%b\n' "\$*"
          }

          run() {
              echo "\${COLOR_PURPLE}==>\${COLOR_OFF} \${COLOR_GREEN}\$@\${COLOR_OFF}"
              eval "\$*"
          }

          run uname -a

          run wget https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
          run chmod a+x ppkg
          run ./ppkg setup --use-system-package-manager
          run ./ppkg update

          sed -i "/git-url/a git-sha: ${{ needs.check.outputs.git-sha }}" ~/.ppkg/repos.d/offical-core/formula/python3-setup.yml

          run ./ppkg install python3-setup gh --link-type=static-only --install-lib=static
          run ./ppkg pack    python3-setup -o .
          EOF

          chmod +x run.sh

      # https://github.com/multiarch/qemu-user-static
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run: docker run -v $PWD:$PWD -w $PWD --name alpine arm64v8/alpine sh run.sh

      - run: ls

      - uses: actions/upload-artifact@v3
        with:
          name: python3-setup---linux-aarch64-tar-xz
          path: python3-setup-*-linux-aarch64.tar.xz


  linux-ppc64le:
    needs: [check, linux-aarch64]
    if: needs.check.outputs.if-has-new-commit == 'yes'

    runs-on: ubuntu-latest

    steps:
      - run: |
          cat > run.sh <<EOF
          set -e

          COLOR_GREEN='\033[0;32m'        # Green
          COLOR_PURPLE='\033[0;35m'       # Purple
          COLOR_OFF='\033[0m'             # Reset

          echo() {
              printf '%b\n' "\$*"
          }

          run() {
              echo "\${COLOR_PURPLE}==>\${COLOR_OFF} \${COLOR_GREEN}\$@\${COLOR_OFF}"
              eval "\$*"
          }

          run uname -a

          run wget https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
          run chmod a+x ppkg
          run ./ppkg setup --use-system-package-manager
          run ./ppkg update

          sed -i "/git-url/a git-sha: ${{ needs.check.outputs.git-sha }}" ~/.ppkg/repos.d/offical-core/formula/python3-setup.yml

          run ./ppkg install python3-setup gh --link-type=static-only --install-lib=static
          run ./ppkg pack    python3-setup -o .
          EOF

          chmod +x run.sh

      # https://github.com/multiarch/qemu-user-static
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run: docker run -v $PWD:$PWD -w $PWD --name alpine ppc64le/alpine sh run.sh

      - run: ls

      - uses: actions/upload-artifact@v3
        with:
          name: python3-setup---linux-ppc64le-tar-xz
          path: python3-setup-*-linux-ppc64le.tar.xz


  linux-s390x:
    needs: [check, linux-ppc64le]
    if: needs.check.outputs.if-has-new-commit == 'yes'

    runs-on: ubuntu-latest

    steps:
      - run: |
          cat > run.sh <<EOF
          set -e

          COLOR_GREEN='\033[0;32m'        # Green
          COLOR_PURPLE='\033[0;35m'       # Purple
          COLOR_OFF='\033[0m'             # Reset

          echo() {
              printf '%b\n' "\$*"
          }

          run() {
              echo "\${COLOR_PURPLE}==>\${COLOR_OFF} \${COLOR_GREEN}\$@\${COLOR_OFF}"
              eval "\$*"
          }

          run uname -a

          run wget https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
          run chmod a+x ppkg
          run ./ppkg setup --use-system-package-manager
          run ./ppkg update

          sed -i "/git-url/a git-sha: ${{ needs.check.outputs.git-sha }}" ~/.ppkg/repos.d/offical-core/formula/python3-setup.yml

          run ./ppkg install python3-setup gh --link-type=static-only --install-lib=static
          run ./ppkg pack    python3-setup -o .
          EOF

          chmod +x run.sh

      # https://github.com/multiarch/qemu-user-static
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run: docker run -v $PWD:$PWD -w $PWD --name alpine s390x/alpine sh run.sh

      - run: ls

      - uses: actions/upload-artifact@v3
        with:
          name: python3-setup---linux-s390x-tar-xz
          path: python3-setup-*-linux-s390x.tar.xz


  linux-x86_64:
    needs: [check, linux-s390x]
    if: needs.check.outputs.if-has-new-commit == 'yes'

    runs-on: ubuntu-latest

    container: alpine:3.16

    steps:
      - run: wget https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg
      - run: ./ppkg setup --use-system-package-manager
      - run: ./ppkg update

      - run: |
          sed -i "/git-url/a git-sha: ${{ needs.check.outputs.git-sha }}" ~/.ppkg/repos.d/offical-core/formula/python3-setup.yml

      - run: ./ppkg install python3-setup --link-type=static-only --install-lib=static
      - run: ./ppkg pack    python3-setup
      - run: cp ~/.ppkg/packed/python3-setup-*-linux-x86_64.tar.xz .

      - uses: actions/upload-artifact@v3
        with:
          name: python3-setup---linux-x86_64-tar-xz
          path: python3-setup-*-linux-x86_64.tar.xz


  publish:
    needs: [check, linux-x86_64]
    if: needs.check.outputs.if-has-new-commit == 'yes'

    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: python3-setup---netbsd-amd64-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: python3-setup---openbsd-amd64-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: python3-setup---freebsd-amd64-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: python3-setup---macos11.0-x86_64-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: python3-setup---macos12.0-x86_64-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: python3-setup---macos13.0-x86_64-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: python3-setup---macos11.0-arm64-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: python3-setup---macos12.0-arm64-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: python3-setup---macos13.0-arm64-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: python3-setup---linux-aarch64-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: python3-setup---linux-ppc64le-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: python3-setup---linux-s390x-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: python3-setup---linux-x86_64-tar-xz
          path: .

      - run: ls -a

      - run: |
          printf 'build-from: https://github.com/leleliu008/python3-setup/tree/%s\n\n' ${{ needs.check.outputs.git-sha }} > notes.md
          printf 'sha256sum:\n```\n%s\n```\n' "$(sha256sum python3-setup-*.tar.xz)" >> notes.md

          VERSION="$(ls python3-setup-*-linux-x86_64.tar.xz | cut -d- -f3)"
          TAGNAME="$VERSION+${{ needs.check.outputs.git-sha }}"

          # to avaid: failed to run git: fatal: not a git repository (or any of the parent directories): .git
          git -c init.defaultBranch=master init
          git remote add origin ${{ github.repositoryUrl }}

          gh release create "$TAGNAME" python3-setup-*.tar.xz --title "$TAGNAME" --notes-file notes.md
