name: Rocky Linux

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        tag: ['8', '9']

    container: rockylinux:${{ matrix.tag }}

    steps:
      - run:  dnf -y update
      - run:  dnf -y install xz gcc-c++
      - run:  |
          command -v curl > /dev/null || dnf -y install curl
          # https://bugs.launchpad.net/tripleo/+bug/1953156

      - uses: actions/checkout@main

      - name: install ppkg
        run: |
          curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
          chmod a+x ppkg
          ./ppkg setup

      - run:  ./ppkg update
      - run:  ./ppkg install python3-setup


      - run:  echo "SSL_CERT_FILE=$HOME/.ppkg/core/etc/ssl/certs/cacert.pem" >> $GITHUB_ENV


      - run: ~/.ppkg/installed/python3-setup/bin/python3-setup

      - run: ~/.ppkg/installed/python3-setup/bin/python3-setup --help
      - run: ~/.ppkg/installed/python3-setup/bin/python3-setup -h

      - run: ~/.ppkg/installed/python3-setup/bin/python3-setup --version
      - run: ~/.ppkg/installed/python3-setup/bin/python3-setup -V

      - run: ~/.ppkg/installed/python3-setup/bin/python3-setup sysinfo

      - run: ~/.ppkg/installed/python3-setup/bin/python3-setup env

      - run: ~/.ppkg/installed/python3-setup/bin/python3-setup show-default-config


      - run: |
          export PATH="$HOME/.uppm/installed/cmake/bin:$PATH"
          ~/.ppkg/installed/python3-setup/bin/python3-setup setup -v

      - run: |
          export PATH="$HOME/.python3-setup/python3/bin:$PATH"
          pip3 install meson

       #- run: ~/.ppkg/installed/python3-setup/bin/python3-setup upgrade-self
